apiVersion: v1
kind: EventListener
metadata:
  name: default
  label:
    en_US: DefaultEventListener
    zh_Hans: DefaultEventListener
    th_TH: DefaultEventListener
    vi_VN: DefaultEventListener
    es_ES: DefaultEventListener
spec:
execution:
  python:
    path: default.py
    attr: DefaultEventListener